name: Terraform Plan (Dev)

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  plan-dev:
    name: Plan dev environment
    runs-on: ubuntu-latest
    env:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      APP_NAME: ${{ vars.APP_NAME }}
      TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
      TF_LOCK_TABLE: ${{ vars.TF_LOCK_TABLE }}
      ARTIFACT_BUCKET: ${{ vars.ARTIFACT_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        working-directory: envs/dev
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: envs/dev
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="dynamodb_table=${TF_LOCK_TABLE}" \
            -backend-config="key=dev/terraform.tfstate"

      - name: Terraform validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform plan
        working-directory: envs/dev
        run: |
          terraform plan \
            -input=false \
            -var "app_name=${APP_NAME}" \
            -var "aws_region=${AWS_REGION}" \
            -var "artifact_bucket=${ARTIFACT_BUCKET}" \
            -var "lambda_s3_key=dummy.zip" \
            -var "lambda_source_code_hash=dummy"
